### ISSUE TITLE
Installing results in FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by ejohb** [jaredks/tweetokenize#5]
Command:

`python.exe -m pip install https://testpypi.python.org/packages/e0/d3/85ec655e244873a487243a80e2c0b248a3c91d6d5b3d2e792715606684c7/tweetokenize-1.0.1.tar.gz`

```
Collecting https://testpypi.python.org/packages/e0/d3/85ec655e244873a487243a80e2c0b248a3c91d6d5b3d2e792715606684c7/tweetokenize-1.0.1.tar.gz
  Downloading https://testpypi.python.org/packages/e0/d3/85ec655e244873a487243a80e2c0b248a3c91d6d5b3d2e792715606684c7/tweetokenize-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Edward\AppData\Local\Temp\pip-cn7l8kbc-build\setup.py", line 13, in <module>
        long_description=open('README.md').read() + '\n\n' + open('CHANGES').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by zhenghy** [comment]
add `include README.md` to file `MANIFEST.in`.
if file no exist , create it.
